[profile.dev]
opt-level = 1
[workspace]
members = [
    "components/conform",
    "components/data-profiler",
    "components/extract",
    "components/load",
    "components/transform"
]
resolver = "2"
