apiVersion: v2
name: retl-orchestration
description: Helm chart for rETL orchestration infrastructure
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: airflow
    version: "1.10.0"
    repository: "https://airflow.apache.org"
    condition: airflow.enabled
  
  - name: spark-operator
    version: "1.1.27"
    repository: "https://googlecloudplatform.github.io/spark-on-k8s-operator"
    condition: sparkOperator.enabled

keywords:
  - etl
  - airflow
  - spark
  - kubernetes
  - data-engineering

maintainers:
  - name: rETL Team
    email: team@retl.dev
