{{- if .Values.serviceAccounts.spark.driver.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.spark.driver.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "retl-orchestration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: spark-driver
---
{{- end }}

{{- if .Values.serviceAccounts.spark.executor.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.spark.executor.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "retl-orchestration.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: spark-executor
---
{{- end }}

# ClusterRole for Spark driver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "retl-orchestration.fullname" . }}-spark-driver
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["*"]

---
# ClusterRoleBinding for Spark driver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "retl-orchestration.fullname" . }}-spark-driver
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.spark.driver.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "retl-orchestration.fullname" . }}-spark-driver
  apiGroup: rbac.authorization.k8s.io
