[package]
name = "extract"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46.0", features = ["lazy", "csv", "json", "parquet"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
