[package]
name = "extract"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.48", features = ["lazy", "csv", "json", "parquet"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
flexi_logger = "0.30.1"

[dev-dependencies]
logtest = "2.0.0"